apiVersion: v1
kind: Pod
metadata:
  name: pod01
spec:
  containers:
  - name: react
    image: duduomena/pipeline:latest
    ports: 
    - containerPort: 3000
---
apiVersion: v1
kind: Pod
metadata:
  name: pod02
  labels: 
    app: react
spec:
  containers:
  - name: react
    image: duduomena/pipeline:latest
    ports: 
    - containerPort: 3000