apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset01
spec:
  replicas: 4
  selector:
    matchLabels:
      app: react
  template: 
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: duduomena/pipeline:latest
        ports: 
        - containerPort: 3000
          hostIP: 192.168.1.40
          nodePort: 30001